[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"