name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r hatlib/requirements.txt
        python -m pip install build
    - name: Build
      run: |
        python -m build
    - name: Publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # redundant, but just in case
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
